// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlIbW8z2SQVeHkEcABOgGBhI65-NxVtl0',
    appId: '1:55883825822:web:1beb6fa80b9af6d563318f',
    messagingSenderId: '55883825822',
    projectId: 'todoapp-215d7',
    authDomain: 'todoapp-215d7.firebaseapp.com',
    storageBucket: 'todoapp-215d7.firebasestorage.app',
    measurementId: 'G-TPBQFP9TLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQCAYwuUU7zvsnKlHc7www3aR32uUayY',
    appId: '1:55883825822:android:067a3ab80ee76cef63318f',
    messagingSenderId: '55883825822',
    projectId: 'todoapp-215d7',
    storageBucket: 'todoapp-215d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSl7_Hej90e8w6P1Yn3Ajh-SuYb5M1hiA',
    appId: '1:55883825822:ios:d8e23f50c39646fe63318f',
    messagingSenderId: '55883825822',
    projectId: 'todoapp-215d7',
    storageBucket: 'todoapp-215d7.firebasestorage.app',
    iosBundleId: 'com.example.todooappnit',
  );
}
